/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificateCertificateIdRouteImport } from './routes/certificate.$certificateId'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateCertificateIdRoute =
  CertificateCertificateIdRouteImport.update({
    id: '/certificate/$certificateId',
    path: '/certificate/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/enterprise': typeof EnterpriseRoute
  '/methodology': typeof MethodologyRoute
  '/scan': typeof ScanRoute
  '/sign-in': typeof SignInRoute
  '/transparency': typeof TransparencyRoute
  '/certificate/$certificateId': typeof CertificateCertificateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/enterprise': typeof EnterpriseRoute
  '/methodology': typeof MethodologyRoute
  '/scan': typeof ScanRoute
  '/sign-in': typeof SignInRoute
  '/transparency': typeof TransparencyRoute
  '/certificate/$certificateId': typeof CertificateCertificateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/enterprise': typeof EnterpriseRoute
  '/methodology': typeof MethodologyRoute
  '/scan': typeof ScanRoute
  '/sign-in': typeof SignInRoute
  '/transparency': typeof TransparencyRoute
  '/certificate/$certificateId': typeof CertificateCertificateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/enterprise'
    | '/methodology'
    | '/scan'
    | '/sign-in'
    | '/transparency'
    | '/certificate/$certificateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/enterprise'
    | '/methodology'
    | '/scan'
    | '/sign-in'
    | '/transparency'
    | '/certificate/$certificateId'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/enterprise'
    | '/methodology'
    | '/scan'
    | '/sign-in'
    | '/transparency'
    | '/certificate/$certificateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  EnterpriseRoute: typeof EnterpriseRoute
  MethodologyRoute: typeof MethodologyRoute
  ScanRoute: typeof ScanRoute
  SignInRoute: typeof SignInRoute
  TransparencyRoute: typeof TransparencyRoute
  CertificateCertificateIdRoute: typeof CertificateCertificateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$certificateId': {
      id: '/certificate/$certificateId'
      path: '/certificate/$certificateId'
      fullPath: '/certificate/$certificateId'
      preLoaderRoute: typeof CertificateCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  EnterpriseRoute: EnterpriseRoute,
  MethodologyRoute: MethodologyRoute,
  ScanRoute: ScanRoute,
  SignInRoute: SignInRoute,
  TransparencyRoute: TransparencyRoute,
  CertificateCertificateIdRoute: CertificateCertificateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
